# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('when', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
