# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='kind',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
